(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
var V={session:null,events:[],tickets:[],profiles:[],tiers:[],current:null};
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function credits(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})+' cr'}
function fmt(v){return v?new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Manual'}
function session(){try{var x=JSON.parse(localStorage.getItem('sb-'+REF+'-auth-token')||'null');return x&&x.access_token?x:(x&&x.currentSession&&x.currentSession.access_token?x.currentSession:(x&&x.session&&x.session.access_token?x.session:null))}catch(e){return null}}
async function req(path,opt){opt=opt||{};var h=Object.assign({'apikey':KEY},opt.headers||{});if(V.session)h.Authorization='Bearer '+V.session.access_token;if(opt.body)h['Content-Type']='application/json';var r=await fetch(BASE+path,Object.assign({},opt,{headers:h}));var txt=await r.text();var d=null;try{d=txt?JSON.parse(txt):null}catch(e){d=txt}if(!r.ok)throw new Error((d&&d.message)||(d&&d.error)||('HTTP '+r.status));return d}
function rest(path,opt){return req('/rest/v1/'+path,opt)}
function rpc(name,args){return rest('rpc/'+name,{method:'POST',body:JSON.stringify(args||{})})}
function status(e){if(e.status==='completed'||e.status==='cancelled'||e.status==='draft')return e.status.toUpperCase();var n=Date.now();if(e.opens_at&&n<new Date(e.opens_at).getTime())return'UPCOMING';if(e.schedule_mode==='manual')return'OPEN';if(e.cutoff_at&&n<new Date(e.cutoff_at).getTime())return'OPEN';return'LOCKED'}
function ticketsFor(id){return V.tickets.filter(function(t){return t.event_id===id})}
function tiersFor(id){return V.tiers.filter(function(t){return t.event_id===id}).sort(function(a,b){return a.rank-b.rank})}
function profile(id){return V.profiles.find(function(p){return p.id===id})||{display_name:'Player',balance:0}}
function balls(t){var h='<div class="v5-balls">';(t.white_numbers||[]).forEach(function(n){h+='<span>'+String(n).padStart(2,'0')+'</span>'});if(t.bonus_ball!=null)h+='<span class="bonus">'+String(t.bonus_ball).padStart(2,'0')+'</span>';return h+'</div>'}
function install(){
  var app=$('app'),tabs=document.querySelector('.tabs');if(!app||!tabs)return;
  if(!$('winners')){var b=document.createElement('button');b.dataset.tab='winners';b.textContent='Winners';tabs.insertBefore(b,tabs.querySelector('[data-tab="players"]'));var s=document.createElement('section');s.id='winners';s.className='tab';s.innerHTML='<article class="panel glass"><div class="panel-head"><div><span class="eyebrow">WINNER MANAGEMENT</span><h2>Winners by event</h2><p>See each winner, all of their winning tickets and adjust their current credit balance.</p></div><button id="v5RefreshWinners" class="btn ghost compact">Refresh</button></div><div id="v5WinnerList" class="v5-winners-grid"></div></article>';var players=$('players');players.parentNode.insertBefore(s,players)}
  if(!$('v5EventGrid')){var grid=document.createElement('div');grid.id='v5EventGrid';grid.className='v5-event-grid';$('eventList').parentNode.insertBefore(grid,$('eventList'))}
  document.body.insertAdjacentHTML('beforeend','<div id="v5Backdrop" class="v5-backdrop" hidden><div id="v5Workspace" class="v5-workspace"></div></div><div id="v5Modal" class="v5-modal" hidden><div id="v5ModalCard" class="v5-modal-card"></div></div>');
  var wb=tabs.querySelector('[data-tab="winners"]');wb.addEventListener('click',function(){document.querySelectorAll('.tabs button').forEach(function(x){x.classList.toggle('active',x===wb)});document.querySelectorAll('.tab').forEach(function(x){x.classList.toggle('active',x.id==='winners')});refresh()});
  tabs.querySelectorAll('button:not([data-tab="winners"])').forEach(function(x){x.addEventListener('click',function(){$('winners').classList.remove('active');wb.classList.remove('active')})});
  $('v5Backdrop').addEventListener('click',function(e){if(e.target===$('v5Backdrop'))closeWorkspace()});
  if($('eventStatusFilter'))$('eventStatusFilter').addEventListener('change',renderEvents);
  if($('v5RefreshWinners'))$('v5RefreshWinners').onclick=refresh;
  refresh();setInterval(refresh,20000);
}
async function refresh(){V.session=session();if(!V.session)return;try{var x=await Promise.all([
  rest('lottery_events?select=*&order=created_at.desc&limit=500'),
  rest('event_tickets?select=id,event_id,user_id,white_numbers,bonus_ball,price_paid,is_winner,winner_rank,prize_awarded,created_at&order=created_at.desc&limit=5000'),
  rest('profiles?select=id,display_name,balance,avatar_url&order=created_at.desc&limit=2000'),
  rest('event_prize_tiers?select=event_id,rank,prize_amount&order=event_id,rank&limit=5000')
]);V.events=x[0]||[];V.tickets=x[1]||[];V.profiles=x[2]||[];V.tiers=x[3]||[];renderEvents();renderWinners();if(V.current){var e=V.events.find(function(z){return z.id===V.current.id});if(e)openWorkspace(e)}}catch(e){console.warn('Admin V5 refresh',e)}}
function renderEvents(){var root=$('v5EventGrid');if(!root)return;var f=$('eventStatusFilter')?$('eventStatusFilter').value:'all';var rows=V.events.filter(function(e){return f==='all'||e.status===f});root.innerHTML='';if(!rows.length){root.innerHTML='<div class="v5-empty">No events found.</div>';return}rows.forEach(function(e){var ts=ticketsFor(e.id),users={};ts.forEach(function(t){users[t.user_id]=1});var card=document.createElement('article');card.className='v5-event-card'+(e.cover_image_url?' has-cover':'');card.innerHTML=(e.cover_image_url?'<div class="v5-event-cover" style="background-image:url(\''+esc(e.cover_image_url)+'\')"></div>':'')+'<div class="v5-event-content"><div class="v5-event-top"><span class="status-pill '+e.status+'">'+esc(status(e))+'</span><span>↗</span></div><h3>'+esc(e.title)+'</h3><p>'+esc(e.description||'Open event workspace')+'</p><div class="v5-event-meta"><span>'+ts.length+' tickets</span><span>'+Object.keys(users).length+' players</span><span>'+Number(e.winner_count||1)+' winners</span><span>'+credits(e.prize_amount)+'</span></div></div>';card.onclick=function(){openWorkspace(e)};root.appendChild(card)})}
function legacyAction(e,label){var d=document.querySelector('#eventList details[data-id="'+CSS.escape(e.id)+'"]');if(!d)return false;var btn=Array.from(d.querySelectorAll('button')).find(function(b){return b.textContent.trim().toLowerCase()===label.toLowerCase()});if(btn){btn.click();closeWorkspace();setTimeout(refresh,1200);return true}return false}
function groupParticipants(e){var ts=ticketsFor(e.id),g={};ts.forEach(function(t){(g[t.user_id]||(g[t.user_id]=[])).push(t)});if(!ts.length)return'<div class="v5-empty">No tickets in this event yet.</div>';return Object.keys(g).map(function(uid){var p=profile(uid),arr=g[uid];return'<div class="v5-participant"><div class="v5-participant-head"><div><strong>'+esc(p.display_name||'Player')+'</strong><span> · '+arr.length+' ticket'+(arr.length===1?'':'s')+'</span></div><span>'+credits(p.balance||0)+'</span></div>'+arr.map(function(t){return'<div class="v5-ticket"><div class="v5-ticket-top"><b>Ticket '+esc(String(t.id).slice(0,8))+'</b>'+(t.is_winner?'<span class="v5-winner-tag">#'+t.winner_rank+' WINNER · '+credits(t.prize_awarded)+'</span>':'')+'</div>'+balls(t)+'</div>'}).join('')+'</div>'}).join('')}
function openWorkspace(e){V.current=e;var ts=ticketsFor(e.id),users={};ts.forEach(function(t){users[t.user_id]=1});var win=ts.filter(function(t){return t.is_winner});var root=$('v5Workspace');root.innerHTML='<button class="v5-close" id="v5Close">×</button><section class="v5-workspace-hero">'+(e.cover_image_url?'<div class="v5-workspace-bg" style="background-image:url(\''+esc(e.cover_image_url)+'\')"></div>':'')+'<div class="v5-workspace-head"><div><span class="eyebrow">EVENT WORKSPACE</span><h2>'+esc(e.title)+'</h2><p>'+esc(e.description||'No description')+'</p></div><span class="status-pill '+e.status+'">'+esc(status(e))+'</span></div></section><div class="v5-workspace-body"><div class="v5-kpis"><div class="v5-kpi"><span>Tickets</span><strong>'+ts.length+'</strong></div><div class="v5-kpi"><span>Players</span><strong>'+Object.keys(users).length+'</strong></div><div class="v5-kpi"><span>Winners</span><strong>'+Number(e.winner_count||1)+'</strong></div><div class="v5-kpi"><span>Ticket price</span><strong>'+credits(e.ticket_price)+'</strong></div><div class="v5-kpi"><span>Total prizes</span><strong>'+credits(e.prize_amount)+'</strong></div></div><div class="v5-actions" id="v5Actions"></div><section class="v5-section"><h3>Ranked prizes</h3><div class="v5-prizes">'+(tiersFor(e.id).map(function(t){return'<div class="v5-prize"><span>#'+t.rank+' WINNER</span><strong>'+credits(t.prize_amount)+'</strong></div>'}).join('')||'<div class="v5-empty">No prize tiers.</div>')+'</div></section>'+(e.status==='completed'?'<section class="v5-section"><h3>Winner summary</h3>'+winnerPeopleHtml(e)+'</section>':'')+'<section class="v5-section"><h3>Players & tickets</h3>'+groupParticipants(e)+'</section></div>';
  var actions=$('v5Actions');addAction(actions,'Public page','ghost',function(){window.open('event.html?e='+encodeURIComponent(e.slug),'_blank')});
  if(e.status==='completed'){addAction(actions,'Edit details','ghost',function(){openCompletedEdit(e)});addAction(actions,'Relaunch as draft','primary',function(){relaunch(e)})}
  else{addAction(actions,'Edit event','ghost',function(){legacyAction(e,'Edit')});if(e.status==='draft')addAction(actions,'Publish','primary',function(){legacyAction(e,'Publish')});if(e.status==='published')addAction(actions,'Run draw','primary',function(){legacyAction(e,'Run draw')});if(e.status==='published'||e.status==='draft')addAction(actions,'Cancel','danger',function(){legacyAction(e,'Cancel')});if((e.status==='draft'||e.status==='cancelled')&&ts.length===0)addAction(actions,'Delete','danger',function(){legacyAction(e,'Delete')})}
  $('v5Close').onclick=closeWorkspace;$('v5Backdrop').hidden=false;document.body.style.overflow='hidden'}
function closeWorkspace(){V.current=null;$('v5Backdrop').hidden=true;document.body.style.overflow=''}
function addAction(root,label,cls,fn){var b=document.createElement('button');b.className='btn '+cls;b.type='button';b.textContent=label;b.onclick=fn;root.appendChild(b)}
function winnerPeopleHtml(e){var wins=ticketsFor(e.id).filter(function(t){return t.is_winner}).sort(function(a,b){return a.winner_rank-b.winner_rank});if(!wins.length)return'<div class="v5-empty">No winner records.</div>';var g={};wins.forEach(function(t){(g[t.user_id]||(g[t.user_id]=[])).push(t)});return Object.keys(g).map(function(uid){var p=profile(uid),arr=g[uid];return'<div class="v5-participant"><div class="v5-participant-head"><div><strong>'+esc(p.display_name||'Player')+'</strong><span> · '+arr.length+' win'+(arr.length===1?'':'s')+'</span></div><span>'+credits(arr.reduce(function(a,t){return a+Number(t.prize_awarded||0)},0))+' prize</span></div>'+arr.map(function(t){return'<div class="v5-ticket"><div class="v5-ticket-top"><b>#'+t.winner_rank+' winning ticket</b><span class="v5-winner-tag">'+credits(t.prize_awarded)+'</span></div>'+balls(t)+'</div>'}).join('')+'</div>'}).join('')}
function renderWinners(){var root=$('v5WinnerList');if(!root)return;var events=V.events.filter(function(e){return e.status==='completed'&&ticketsFor(e.id).some(function(t){return t.is_winner})});if(!events.length){root.innerHTML='<div class="v5-empty">No completed-event winners yet.</div>';return}root.innerHTML=events.map(function(e){var wins=ticketsFor(e.id).filter(function(t){return t.is_winner}),g={};wins.forEach(function(t){(g[t.user_id]||(g[t.user_id]=[])).push(t)});return'<section class="v5-winner-event"><h3>'+esc(e.title)+'</h3>'+Object.keys(g).map(function(uid){var p=profile(uid),arr=g[uid],sum=arr.reduce(function(a,t){return a+Number(t.prize_awarded||0)},0);return'<div class="v5-winner-person"><div class="v5-winner-person-head"><div><strong>'+esc(p.display_name||'Player')+'</strong><span>'+arr.length+' winning ticket'+(arr.length===1?'':'s')+' · Prize '+credits(sum)+'</span></div><span>Balance '+credits(p.balance||0)+'</span></div><div>'+arr.map(function(t){return'<div class="v5-ticket"><div class="v5-ticket-top"><b>#'+t.winner_rank+'</b><span>'+credits(t.prize_awarded)+'</span></div>'+balls(t)+'</div>'}).join('')+'</div><button class="btn ghost compact v5-balance-btn" data-balance-user="'+esc(uid)+'">Edit credits</button></div>'}).join('')+'</section>'}).join('');root.querySelectorAll('[data-balance-user]').forEach(function(b){b.onclick=function(){openBalance(b.dataset.balanceUser)}})}
function openCompletedEdit(e){var m=$('v5Modal'),c=$('v5ModalCard');c.innerHTML='<h3>Edit completed event</h3><p style="color:#8f9aa4;font-size:13px">Historical tickets, winner ranks and awarded prizes stay locked. You can safely edit public metadata, or relaunch the event as a fresh draft.</p><form id="v5CompletedForm"><label>Title<input id="v5Title" required value="'+esc(e.title)+'"></label><label>Public slug<input id="v5Slug" required value="'+esc(e.slug)+'"></label><label>Description<textarea id="v5Desc">'+esc(e.description||'')+'</textarea></label><div class="v5-modal-actions"><button type="button" class="btn ghost" id="v5CancelModal">Cancel</button><button type="submit" class="btn primary">Save changes</button></div></form>';m.hidden=false;$('v5CancelModal').onclick=closeModal;$('v5CompletedForm').onsubmit=async function(ev){ev.preventDefault();try{await rpc('admin_update_completed_event_metadata',{p_event_id:e.id,p_title:$('v5Title').value,p_slug:$('v5Slug').value,p_description:$('v5Desc').value});closeModal();closeWorkspace();await refresh()}catch(err){alert(err.message)}}}
async function relaunch(e){if(!confirm('Create a fresh draft from this completed event? Old tickets and winners will remain untouched.'))return;try{await rpc('admin_relaunch_lottery_event',{p_event_id:e.id});closeWorkspace();await refresh();alert('Relaunch draft created. Open it from Events & Tickets to edit and publish.')}catch(err){alert(err.message)}}
function openBalance(uid){var p=profile(uid),m=$('v5Modal'),c=$('v5ModalCard');c.innerHTML='<h3>Edit winner credits</h3><p style="color:#8f9aa4;font-size:13px">'+esc(p.display_name||'Player')+'</p><form id="v5BalanceForm"><label>Current balance<input id="v5Balance" type="number" min="0" step="1" value="'+Number(p.balance||0)+'" required></label><label>Admin note<input id="v5BalanceNote" value="Winner balance adjustment"></label><div class="v5-modal-actions"><button type="button" class="btn ghost" id="v5CancelModal">Cancel</button><button type="submit" class="btn primary">Update credits</button></div></form>';m.hidden=false;$('v5CancelModal').onclick=closeModal;$('v5BalanceForm').onsubmit=async function(ev){ev.preventDefault();try{await rpc('admin_set_user_balance',{p_user_id:uid,p_balance:Number($('v5Balance').value),p_note:$('v5BalanceNote').value});closeModal();await refresh()}catch(err){alert(err.message)}}}
function closeModal(){$('v5Modal').hidden=true}
function wait(){var n=0,t=setInterval(function(){n++;if($('app')&&!$('app').hidden&&$('eventList')){clearInterval(t);install()}else if(n>80)clearInterval(t)},150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait);else wait();
})();