(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var TOKEN_KEY='draw01_support_bridge_token';
var installPrompt=null;
function $(id){return document.getElementById(id)}
function msg(t,err){var n=$('bridgeStatus');n.textContent=t||'';n.className='bridge-status'+(err?' err':'')}
function maskNumber(raw){var m=String(raw||'').match(/(?:\+?8801\d{9}|01\d{9})/);if(!m)return '—';var n=m[0].replace(/\D/g,'');return '*******'+n.slice(-4)}
function localPreview(raw){var t=String(raw||'');var trx=(t.match(/trx\s*id\s*[:\-]?\s*([A-Za-z0-9]{6,32})/i)||[])[1];var amount=(t.match(/received\s*(?:tk\.?|bdt|৳)?\s*([0-9,]+(?:\.[0-9]{1,2})?)/i)||t.match(/(?:tk\.?|bdt|৳)\s*([0-9,]+(?:\.[0-9]{1,2})?)\s*(?:has\s+been\s+)?received/i)||[])[1];var sender=(t.match(/from\s*(\+?8801\d{9}|01\d{9})/i)||[])[1];var p=$('bridgePreview');if(!trx&&!amount&&!sender){p.classList.remove('show');return}p.classList.add('show');$('pvAmount').textContent=amount?'৳'+amount:'—';$('pvSender').textContent=maskNumber(sender);$('pvTrx').textContent=trx||'—'}
function saveToken(){var v=$('bridgeToken').value.trim();if(v.length<20){msg('Paste the device token generated from Admin Panel.',true);return}localStorage.setItem(TOKEN_KEY,v);msg('Device token saved on this phone only.')}
function clearToken(){localStorage.removeItem(TOKEN_KEY);$('bridgeToken').value='';msg('Saved device token removed from this phone.')}
function sync(){var token=$('bridgeToken').value.trim()||localStorage.getItem(TOKEN_KEY)||'';var raw=$('bridgeSms').value.trim();if(token.length<20){msg('Device token is missing. Generate one from Admin Panel and save it here.',true);return}if(raw.length<20){msg('Paste or share the received-money bKash SMS first.',true);return}var b=$('bridgeSync');b.disabled=true;b.textContent='Syncing…';msg('');fetch(BASE+'/functions/v1/support-phone-bridge',{method:'POST',headers:{'Content-Type':'application/json','x-bridge-token':token},body:JSON.stringify({rawSms:raw,receivedAt:new Date().toISOString()})}).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.error)||(d&&d.message)||('HTTP '+r.status));return d})}).then(function(d){localStorage.setItem(TOKEN_KEY,token);$('bridgeSms').value='';localPreview('');$('bridgePreview').classList.add('show');$('pvAmount').textContent='৳'+Number(d.amount||0).toLocaleString(undefined,{maximumFractionDigits:2});$('pvSender').textContent=d.senderMasked||'Verified';$('pvTrx').textContent=d.trxId||'—';msg('Synced to cloud ✓ Now open DRAW//01 → Credit → Support Points and claim using sender number + TrxID.')}).catch(function(e){msg(e.message,true)}).finally(function(){b.disabled=false;b.textContent='Sync SMS to cloud'})}
function init(){var saved=localStorage.getItem(TOKEN_KEY)||'';$('bridgeToken').value=saved;$('saveToken').onclick=saveToken;$('clearToken').onclick=clearToken;$('bridgeSync').onclick=sync;$('bridgeSms').addEventListener('input',function(){localPreview(this.value)});var q=new URLSearchParams(location.search);var shared=q.get('text')||q.get('title')||'';if(shared){$('bridgeSms').value=shared;localPreview(shared);msg('Shared SMS loaded. Review it, then tap “Sync SMS to cloud”.')}if('serviceWorker' in navigator)navigator.serviceWorker.register('bridge-sw.js').catch(function(){});$('installBridge').onclick=function(){if(installPrompt){installPrompt.prompt();installPrompt.userChoice.finally(function(){installPrompt=null;$('installBridge').hidden=true})}else msg('On Android Chrome, use ⋮ → Add to Home screen / Install app.')}}
window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();installPrompt=e;if($('installBridge'))$('installBridge').hidden=false});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();