(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
var C={session:null,user:null,profile:null,requests:[]};
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function money(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})+' credits'}
function readSession(){try{var keys=['sb-'+REF+'-auth-token'];for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(REF)>=0&&k.indexOf('auth')>=0&&keys.indexOf(k)<0)keys.push(k)}for(var j=0;j<keys.length;j++){var raw=localStorage.getItem(keys[j]);if(!raw)continue;try{var x=JSON.parse(raw),s=x&&x.access_token?x:(x&&x.currentSession&&x.currentSession.access_token?x.currentSession:(x&&x.session&&x.session.access_token?x.session:null));if(s)return s}catch(e){}}return null}catch(e){return null}}
function req(path,opt){opt=opt||{};var h=Object.assign({apikey:KEY},opt.headers||{});if(C.session&&C.session.access_token)h.Authorization='Bearer '+C.session.access_token;if(opt.body)h['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:h})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.message)||(d&&d.details)||(d&&d.error_description)||(d&&d.error)||('HTTP '+r.status));return d})})}
function install(){if($('d01CreditCenter'))return;document.body.insertAdjacentHTML('beforeend','<div id="d01CreditCenter" class="d01-credit-center" hidden><section class="dcc-shell" role="dialog" aria-modal="true" aria-labelledby="dccTitle"><header class="dcc-head"><div><small>VIRTUAL CREDIT CENTER</small><h2 id="dccTitle">Credits & Requests</h2><p>Request test credits and follow approval status from one place.</p></div><button class="dcc-close" id="dccClose" type="button" aria-label="Close">×</button></header><div class="dcc-body"><div class="dcc-top"><article class="dcc-summary"><span>Current balance</span><strong id="dccBalance">0 credits</strong><p>Balance updates after an admin approves a request.</p></article><article class="dcc-safety"><strong>Simulation credits only</strong><p>No bKash/Nagad payment, deposit, withdrawal, cash prize or real-money wagering is processed here. Credits have no cash value.</p></article></div><div class="dcc-grid"><article class="dcc-panel"><h3>Request virtual credits</h3><p>Send a request to the admin. Only approved requests change your balance.</p><form id="dccForm"><label class="dcc-label"><span>Credits requested</span><input id="dccAmount" type="number" min="1" max="100000" step="1" required placeholder="e.g. 100"></label><div class="dcc-quick"><button type="button" class="dcc-chip" data-v="50">50</button><button type="button" class="dcc-chip" data-v="100">100</button><button type="button" class="dcc-chip" data-v="250">250</button><button type="button" class="dcc-chip" data-v="500">500</button></div><label class="dcc-label"><span>Note (optional)</span><textarea id="dccNote" maxlength="500" placeholder="Why do you need test credits?"></textarea></label><button id="dccSubmit" class="dcc-submit" type="submit">Submit credit request</button><div id="dccMessage" class="dcc-message"></div><div class="dcc-note">Only one pending request is allowed at a time. Admin approval is required.</div></form></article><article class="dcc-panel"><h3>Request history</h3><p>Your recent credit requests and their review status.</p><div id="dccHistory" class="dcc-history"><div class="dcc-empty">Loading requests…</div></div></article></div></div></section></div>');
$('dccClose').onclick=close;var center=$('d01CreditCenter');center.addEventListener('click',function(e){if(e.target===center)close()});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!center.hidden)close()});document.querySelectorAll('.dcc-chip').forEach(function(b){b.onclick=function(){$('dccAmount').value=b.dataset.v}});$('dccForm').onsubmit=submit}
function msg(t,err){var m=$('dccMessage');if(!m)return;m.textContent=t||'';m.className='dcc-message'+(err?' err':'')}
function fmt(v){return v?new Date(v).toLocaleString([], {month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'—'}
function renderHistory(){var root=$('dccHistory');if(!root)return;if(!C.requests.length){root.innerHTML='<div class="dcc-empty">No credit requests yet.</div>';return}root.innerHTML=C.requests.map(function(r){return '<article class="dcc-request"><div class="dcc-request-top"><strong>'+esc(money(r.requested_credits))+'</strong><span class="dcc-status '+esc(r.status)+'">'+esc(String(r.status).toUpperCase())+'</span></div><div class="dcc-request-meta"><span>'+esc(fmt(r.created_at))+'</span>'+(r.reviewed_at?'<span>Reviewed '+esc(fmt(r.reviewed_at))+'</span>':'')+'</div>'+(r.note?'<div class="dcc-request-note">'+esc(r.note)+'</div>':'')+(r.admin_note?'<div class="dcc-request-note"><b>Admin:</b> '+esc(r.admin_note)+'</div>':'')+'</article>'}).join('')}
function load(){C.session=readSession();if(!C.session){msg('Please sign in with Google first.',true);return Promise.reject(new Error('No active session'))}return req('/auth/v1/user').then(function(u){C.user=u;return Promise.all([req('/rest/v1/profiles?select=id,display_name,balance&id=eq.'+encodeURIComponent(u.id)+'&limit=1'),req('/rest/v1/credit_requests?select=id,user_id,requested_credits,note,status,admin_note,created_at,reviewed_at&user_id=eq.'+encodeURIComponent(u.id)+'&order=created_at.desc&limit=30')])}).then(function(x){C.profile=x[0]&&x[0][0]?x[0][0]:null;C.requests=x[1]||[];if($('dccBalance'))$('dccBalance').textContent=money(C.profile&&C.profile.balance||0);renderHistory();var pending=C.requests.some(function(r){return r.status==='pending'});$('dccSubmit').disabled=pending;$('dccSubmit').textContent=pending?'Request pending':'Submit credit request';if(pending)msg('You already have a pending request.');else msg('');}).catch(function(e){msg(e.message,true)})}
function submit(e){e.preventDefault();var n=Number($('dccAmount').value),note=$('dccNote').value.trim();if(!Number.isFinite(n)||n<=0||n>100000){msg('Enter a valid credit amount between 1 and 100,000.',true);return}if(!C.user){msg('Please sign in first.',true);return}$('dccSubmit').disabled=true;$('dccSubmit').textContent='Submitting…';req('/rest/v1/credit_requests',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:C.user.id,requested_credits:n,note:note||null})}).then(function(){$('dccAmount').value='';$('dccNote').value='';msg('Credit request submitted. Admin review is required.');return load()}).catch(function(err){msg(/duplicate key|pending/i.test(err.message)?'You already have a pending request.':err.message,true);$('dccSubmit').disabled=false;$('dccSubmit').textContent='Submit credit request'})}
function open(){install();var c=$('d01CreditCenter');c.hidden=false;document.body.style.overflow='hidden';load()}
function close(){var c=$('d01CreditCenter');if(c)c.hidden=true;document.body.style.overflow=''}
window.Draw01CreditCenter={open:open,close:close,refresh:load};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();