(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
function session(){try{var x=JSON.parse(localStorage.getItem('sb-'+REF+'-auth-token')||'null');return x&&x.access_token?x:(x&&x.currentSession&&x.currentSession.access_token?x.currentSession:(x&&x.session&&x.session.access_token?x.session:null))}catch(e){return null}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function req(path,opt){opt=opt||{};var s=session(),h=Object.assign({apikey:KEY},opt.headers||{});if(s&&s.access_token)h.Authorization='Bearer '+s.access_token;if(opt.body)h['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:h})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.message)||(d&&d.error)||('HTTP '+r.status));return d})})}
function install(){var players=document.getElementById('players');if(!players||document.getElementById('creditAdminBox'))return;var panel=players.querySelector('.panel');if(!panel)return;var box=document.createElement('section');box.id='creditAdminBox';box.className='credit-admin-box';box.innerHTML='<div class="credit-admin-head"><div><h3>Virtual Credit Requests</h3><p>Approve or reject user requests. Approval adds credits to the user balance and ledger.</p></div><span id="creditAdminCount" class="credit-admin-count">0 pending</span></div><div id="creditAdminList" class="credit-admin-list"><div class="credit-admin-empty">Loading requests…</div></div>';var anchor=panel.querySelector('#playerList');panel.insertBefore(box,anchor);load()}
function load(){var s=session(),root=document.getElementById('creditAdminList');if(!s||!root)return;Promise.all([
req('/rest/v1/credit_requests?select=id,user_id,requested_credits,note,status,admin_note,created_at,reviewed_at&order=created_at.desc&limit=100'),
req('/rest/v1/profiles?select=id,display_name,email,balance&limit=2000')
]).then(function(x){var reqs=x[0]||[],profiles=x[1]||[],pm={};profiles.forEach(function(p){pm[p.id]=p});var pending=reqs.filter(function(r){return r.status==='pending'});document.getElementById('creditAdminCount').textContent=pending.length+' pending';if(!reqs.length){root.innerHTML='<div class="credit-admin-empty">No credit requests yet.</div>';return}root.innerHTML=reqs.slice(0,40).map(function(r){var p=pm[r.user_id]||{},actions=r.status==='pending'?'<div class="credit-admin-actions"><button class="credit-approve" data-credit-action="approve" data-id="'+esc(r.id)+'">Approve</button><button class="credit-reject" data-credit-action="reject" data-id="'+esc(r.id)+'">Reject</button></div>':'<div class="credit-admin-actions"><span class="status-pill '+esc(r.status)+'">'+esc(r.status.toUpperCase())+'</span></div>';return '<article class="credit-admin-row"><div class="credit-admin-main"><strong>'+esc(p.display_name||p.email||'Player')+' · '+Number(r.requested_credits||0).toLocaleString()+' credits</strong><span>Current balance '+Number(p.balance||0).toLocaleString()+' · '+new Date(r.created_at).toLocaleString()+'</span>'+(r.note?'<em>'+esc(r.note)+'</em>':'')+(r.admin_note?'<em>Admin: '+esc(r.admin_note)+'</em>':'')+'</div>'+actions+'</article>'}).join('');root.querySelectorAll('[data-credit-action]').forEach(function(b){b.onclick=function(){review(b.dataset.id,b.dataset.creditAction==='approve')}})}).catch(function(e){root.innerHTML='<div class="credit-admin-empty">'+esc(e.message)+'</div>'})}
function review(id,approve){var note=prompt(approve?'Optional approval note:':'Reason for rejection (optional):','')||'';if(approve&&!confirm('Approve this virtual credit request and add the requested credits to the user balance?'))return;req('/rest/v1/rpc/admin_review_credit_request',{method:'POST',body:JSON.stringify({p_request_id:id,p_approve:approve,p_note:note||null})}).then(function(){load();if(window.Draw01Shell)window.Draw01Shell.refresh();setTimeout(function(){if(typeof location!=='undefined')location.reload()},500)}).catch(function(e){alert(e.message)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(install,900)});else setTimeout(install,900);
})();