(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co',KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd',REF='mwtlsnneooxmryondrex';
var X={session:null,events:[],tickets:[],profiles:[],editing:null,balanceUser:null,renderingPlayers:false};
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function credits(v){return Number(v||0).toLocaleString()+' credits'}
function fmt(v){return v?new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—'}
function localInput(v){if(!v)return'';var d=new Date(v);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function session(){try{var s=JSON.parse(localStorage.getItem('sb-'+REF+'-auth-token')||'null');return s&&s.access_token?s:(s&&s.currentSession&&s.currentSession.access_token?s.currentSession:null)}catch(e){return null}}
function req(path,opt){opt=opt||{};var h=opt.headers||{};h.apikey=KEY;if(X.session)h.Authorization='Bearer '+X.session.access_token;if(opt.body)h['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:h})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.message)||(d&&d.error)||('HTTP '+r.status));return d})})}
function rest(path,opt){return req('/rest/v1/'+path,opt)}
function rpc(name,args){return rest('rpc/'+name,{method:'POST',body:JSON.stringify(args||{})})}
function note(m,e){var t=$('toast');if(!t)return;t.textContent=m;t.className=e?'err':'';t.style.display='block';clearTimeout(t._eh);t._eh=setTimeout(function(){t.style.display='none'},3800)}
function slugify(v){return String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
function statusTime(e){var n=Date.now();if(e.status==='completed')return'Completed';if(e.status==='cancelled')return'Cancelled';if(e.status==='draft')return'Draft';if(n<new Date(e.opens_at).getTime())return'Upcoming';if(n<new Date(e.cutoff_at).getTime())return'Open';if(n<new Date(e.draw_at).getTime())return'Locked';return'Awaiting draw'}
function countTickets(id){return X.tickets.filter(function(t){return t.event_id===id}).length}

function injectStyle(){if(document.querySelector('link[data-ops-events]'))return;var l=document.createElement('link');l.rel='stylesheet';l.href='ops-events.css?v=1';l.dataset.opsEvents='1';document.head.appendChild(l)}
function buildModals(){if($('lotteryEventDialog'))return;var wrap=document.createElement('div');wrap.innerHTML=`
<dialog id="lotteryEventDialog" class="event-form-modal"><form id="lotteryEventForm" class="event-form-card glass">
  <div class="panel-head"><div><span class="eyebrow" id="lotteryModalKicker">CREATE LOTTERY EVENT</span><h2 id="lotteryModalTitle">New public event</h2></div><button type="button" id="closeLotteryEvent" class="icon-btn">×</button></div>
  <div class="event-form-grid">
    <label><span>Event title</span><input id="leTitle" required placeholder="Friday Mega Draw"></label>
    <label><span>Public slug</span><input id="leSlug" placeholder="friday-mega-draw"></label>
    <label class="full"><span>Description</span><textarea id="leDescription" placeholder="Describe this event for players."></textarea></label>
    <label><span>Ticket price (credits)</span><input id="lePrice" type="number" min="0" step="1" value="10" required></label>
    <label><span>Prize pool (credits)</span><input id="lePrize" type="number" min="0" step="1" value="1000" required></label>
    <label><span>Prize mode</span><select id="lePrizeMode"><option value="split_pool">Split pool across winning tickets</option><option value="fixed_per_winning_ticket">Fixed prize per winning ticket</option></select></label>
    <label><span>Max tickets per player</span><input id="leLimit" type="number" min="1" max="1000" value="5" required></label>
    <label><span>White numbers to pick</span><input id="leWhiteCount" type="number" min="1" max="10" value="5" required></label>
    <label><span>White number range max</span><input id="leWhiteMax" type="number" min="2" max="500" value="69" required></label>
    <label class="inline-check"><input id="leBonusEnabled" type="checkbox" checked><span>Use bonus ball</span></label>
    <label><span>Bonus ball range max</span><input id="leBonusMax" type="number" min="1" max="500" value="26" required></label>
    <label><span>Opens at</span><input id="leOpen" type="datetime-local" required></label>
    <label><span>Ticket cutoff</span><input id="leCutoff" type="datetime-local" required></label>
    <label><span>Draw time</span><input id="leDraw" type="datetime-local" required></label>
    <label><span>Status</span><select id="leStatus"><option value="draft">Draft</option><option value="published">Published</option><option value="cancelled">Cancelled</option></select></label>
  </div>
  <div class="event-modal-actions"><button type="button" id="cancelLotteryEvent" class="btn ghost">Cancel</button><button type="submit" class="btn primary" id="saveLotteryEvent">Create event</button></div>
</form></dialog>
<dialog id="balanceDialog" class="balance-modal"><form id="balanceForm" class="balance-card glass">
  <span class="eyebrow">VIRTUAL CREDIT BALANCE</span><h2 id="balanceTitle">Set balance</h2><p id="balanceEmail"></p>
  <label>New balance<input id="balanceInput" type="number" min="0" step="1" required></label>
  <label>Admin note<input id="balanceNote" placeholder="Manual test credit"></label>
  <div class="event-modal-actions"><button type="button" id="cancelBalance" class="btn ghost">Cancel</button><button type="submit" class="btn primary">Update balance</button></div>
</form></dialog>`;
while(wrap.firstChild)document.body.appendChild(wrap.firstChild);
$('closeLotteryEvent').onclick=$('cancelLotteryEvent').onclick=function(){$('lotteryEventDialog').close()};$('cancelBalance').onclick=function(){$('balanceDialog').close()};$('lotteryEventForm').onsubmit=saveEvent;$('balanceForm').onsubmit=saveBalance;$('leTitle').addEventListener('input',function(){if(!X.editing&&!$('leSlug').dataset.touched)$('leSlug').value=slugify(this.value)});$('leSlug').addEventListener('input',function(){this.dataset.touched='1'})
}

function replaceEventSection(){var sec=$('events');if(!sec)return;var tab=document.querySelector('[data-tab="events"]');if(tab)tab.textContent='Events';sec.innerHTML=`<article class="panel glass"><div class="panel-head"><div><span class="eyebrow">LOTTERY EVENT MANAGEMENT</span><h2>Public events</h2><p>Create event-specific ticket pricing, prizes, limits, number rules and schedules.</p></div><button id="createLotteryEvent" class="btn primary">+ Create event</button></div><div class="event-admin-toolbar"><span id="lotterySummary" class="muted-pill">0 events</span><div><button id="refreshLotteryEvents" class="btn ghost compact">Refresh</button></div></div><div id="lotteryEventList"></div></article>`;$('createLotteryEvent').onclick=openCreateEvent;$('refreshLotteryEvents').onclick=loadEvents;
  ['newDrawTop','heroNewDraw'].forEach(function(id){var b=$(id);if(b){b.textContent='+ New event';b.onclick=openCreateEvent}})
}

function loadEvents(){return Promise.all([rest('lottery_events?select=*&order=created_at.desc&limit=200'),rest('event_tickets?select=id,event_id,user_id,price_paid,is_winner,prize_awarded,created_at&order=created_at.desc&limit=2000')]).then(function(x){X.events=x[0]||[];X.tickets=x[1]||[];renderEvents()}).catch(function(e){note('Event load failed: '+e.message,true)})}
function renderEvents(){var root=$('lotteryEventList');if(!root)return;$('lotterySummary').textContent=X.events.length+' events';root.innerHTML='';if(!X.events.length){root.innerHTML='<div class="record-card"><div class="record-main"><strong>No lottery events yet</strong><div class="record-meta"><span>Create the first event to publish it on the public dashboard.</span></div></div></div>';return}X.events.forEach(function(e){var row=document.createElement('div');row.className='lottery-record';var left=document.createElement('div');left.innerHTML='<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><h3>'+esc(e.title)+'</h3><span class="admin-event-status '+esc(e.status)+'">'+esc(statusTime(e).toUpperCase())+'</span></div><div class="meta"><span>Ticket <b>'+credits(e.ticket_price)+'</b></span><span>Prize <b>'+credits(e.prize_amount)+'</b></span><span>Limit <b>'+e.max_tickets_per_user+'</b></span><span>Entries <b>'+countTickets(e.id)+'</b></span><span>Draw <b>'+esc(fmt(e.draw_at))+'</b></span></div>';var a=document.createElement('div');a.className='lottery-actions';a.appendChild(button('View','ghost',function(){window.open('event.html?e='+encodeURIComponent(e.slug),'_blank')}));if(e.status!=='completed')a.appendChild(button('Edit','ghost',function(){openEditEvent(e)}));if(e.status==='draft')a.appendChild(button('Publish','primary',function(){updateStatus(e,'published')}));if(e.status==='published'&&Date.now()>=new Date(e.cutoff_at).getTime())a.appendChild(button('Run draw','primary',function(){runEvent(e)}));if(e.status!=='completed'&&e.status!=='cancelled')a.appendChild(button('Cancel','danger',function(){updateStatus(e,'cancelled')}));row.appendChild(left);row.appendChild(a);root.appendChild(row)})}
function button(label,cls,fn){var b=document.createElement('button');b.type='button';b.className='btn '+(cls||'ghost')+' compact';b.textContent=label;b.onclick=fn;return b}

function defaults(){var n=Date.now();return{open:new Date(n+60000),cut:new Date(n+10*60000),draw:new Date(n+11*60000)}}
function openCreateEvent(){X.editing=null;var d=defaults();$('lotteryModalKicker').textContent='CREATE LOTTERY EVENT';$('lotteryModalTitle').textContent='New public event';$('saveLotteryEvent').textContent='Create event';$('leTitle').value='';$('leSlug').value='';delete $('leSlug').dataset.touched;$('leDescription').value='';$('lePrice').value=10;$('lePrize').value=1000;$('lePrizeMode').value='split_pool';$('leLimit').value=5;$('leWhiteCount').value=5;$('leWhiteMax').value=69;$('leBonusEnabled').checked=true;$('leBonusMax').value=26;$('leOpen').value=localInput(d.open);$('leCutoff').value=localInput(d.cut);$('leDraw').value=localInput(d.draw);$('leStatus').value='published';$('lotteryEventDialog').showModal()}
function openEditEvent(e){X.editing=e;$('lotteryModalKicker').textContent='EDIT LOTTERY EVENT';$('lotteryModalTitle').textContent=e.title;$('saveLotteryEvent').textContent='Save changes';$('leTitle').value=e.title||'';$('leSlug').value=e.slug||'';$('leSlug').dataset.touched='1';$('leDescription').value=e.description||'';$('lePrice').value=Number(e.ticket_price);$('lePrize').value=Number(e.prize_amount);$('lePrizeMode').value=e.prize_mode;$('leLimit').value=e.max_tickets_per_user;$('leWhiteCount').value=e.white_ball_count;$('leWhiteMax').value=e.white_ball_max;$('leBonusEnabled').checked=!!e.bonus_ball_enabled;$('leBonusMax').value=e.bonus_ball_max;$('leOpen').value=localInput(e.opens_at);$('leCutoff').value=localInput(e.cutoff_at);$('leDraw').value=localInput(e.draw_at);$('leStatus').value=e.status==='completed'?'published':e.status;$('lotteryEventDialog').showModal()}
function formArgs(){return{p_title:$('leTitle').value.trim(),p_slug:$('leSlug').value.trim()||slugify($('leTitle').value),p_description:$('leDescription').value.trim(),p_ticket_price:Number($('lePrice').value),p_prize_amount:Number($('lePrize').value),p_prize_mode:$('lePrizeMode').value,p_max_tickets_per_user:Number($('leLimit').value),p_white_ball_count:Number($('leWhiteCount').value),p_white_ball_max:Number($('leWhiteMax').value),p_bonus_ball_enabled:$('leBonusEnabled').checked,p_bonus_ball_max:Number($('leBonusMax').value),p_opens_at:new Date($('leOpen').value).toISOString(),p_cutoff_at:new Date($('leCutoff').value).toISOString(),p_draw_at:new Date($('leDraw').value).toISOString()}}
function saveEvent(ev){ev.preventDefault();var a=formArgs(),promise;if(X.editing){a.p_event_id=X.editing.id;a.p_status=$('leStatus').value;promise=rpc('admin_update_lottery_event',a)}else{a.p_publish=$('leStatus').value==='published';promise=rpc('admin_create_lottery_event',a)}$('saveLotteryEvent').disabled=true;promise.then(function(){$('lotteryEventDialog').close();note(X.editing?'Event updated':'Event created');X.editing=null;return loadEvents()}).catch(function(e){note(e.message,true)}).finally(function(){$('saveLotteryEvent').disabled=false})}
function updateStatus(e,status){var a={p_event_id:e.id,p_title:e.title,p_slug:e.slug,p_description:e.description||'',p_ticket_price:Number(e.ticket_price),p_prize_amount:Number(e.prize_amount),p_prize_mode:e.prize_mode,p_max_tickets_per_user:e.max_tickets_per_user,p_white_ball_count:e.white_ball_count,p_white_ball_max:e.white_ball_max,p_bonus_ball_enabled:e.bonus_ball_enabled,p_bonus_ball_max:e.bonus_ball_max,p_opens_at:e.opens_at,p_cutoff_at:e.cutoff_at,p_draw_at:e.draw_at,p_status:status};rpc('admin_update_lottery_event',a).then(function(){note('Event '+status);loadEvents()}).catch(function(x){note(x.message,true)})}
function runEvent(e){if(!confirm('Run this secure event draw now? Admin cannot choose the winning numbers.'))return;rpc('admin_run_lottery_event',{p_event_id:e.id}).then(function(){note('Event draw completed');loadEvents();loadProfiles()}).catch(function(x){note(x.message,true)})}

function loadProfiles(){return rest('profiles?select=id,display_name,email,role,created_at,balance&order=created_at.desc&limit=500').then(function(p){X.profiles=p||[];renderCreditPlayers()}).catch(function(e){note('Balance load failed: '+e.message,true)})}
function renderCreditPlayers(){var root=$('playerList');if(!root||X.renderingPlayers)return;X.renderingPlayers=true;root.innerHTML='';X.profiles.forEach(function(p){var row=document.createElement('div');row.className='record-card';var left=document.createElement('div');left.className='record-main';left.innerHTML='<div class="record-title"><strong>'+esc(p.display_name||'Player')+'</strong><span class="status-pill">'+esc((p.role||'player').toUpperCase())+'</span></div><div class="record-meta"><span>'+esc(p.email||'')+'</span><span class="credit-balance">'+credits(p.balance)+'</span></div>';var actions=document.createElement('div');actions.className='record-actions';actions.appendChild(button('Set balance','primary',function(){openBalance(p)}));var role=document.createElement('select');role.className='role-select';role.innerHTML='<option value="player">Player</option><option value="admin">Admin</option>';role.value=p.role;var own=X.session&&X.session.user&&p.id===X.session.user.id;role.disabled=!!own;role.onchange=function(){rpc('admin_set_user_role',{p_user_id:p.id,p_role:role.value}).then(function(){note('Role updated');loadProfiles()}).catch(function(e){note(e.message,true)})};actions.appendChild(role);row.appendChild(left);row.appendChild(actions);root.appendChild(row)});root.dataset.creditMode='1';X.renderingPlayers=false}
function openBalance(p){X.balanceUser=p;$('balanceTitle').textContent=p.display_name||'Player';$('balanceEmail').textContent=(p.email||'')+' · Current '+credits(p.balance);$('balanceInput').value=Number(p.balance||0);$('balanceNote').value='';$('balanceDialog').showModal()}
function saveBalance(e){e.preventDefault();if(!X.balanceUser)return;rpc('admin_set_user_balance',{p_user_id:X.balanceUser.id,p_balance:Number($('balanceInput').value),p_note:$('balanceNote').value.trim()||'Admin balance update'}).then(function(){$('balanceDialog').close();note('Balance updated');return loadProfiles()}).catch(function(x){note(x.message,true)})}

function watchPlayers(){var root=$('playerList');if(!root)return;var obs=new MutationObserver(function(){if(X.renderingPlayers)return;if(!root.querySelector('.credit-balance')&&X.profiles.length)setTimeout(renderCreditPlayers,0)});obs.observe(root,{childList:true,subtree:false})}
function init(){X.session=session();if(!X.session)return;injectStyle();buildModals();replaceEventSection();loadEvents();setTimeout(function(){loadProfiles();watchPlayers()},800);setInterval(function(){if($('lotteryEventList'))renderEvents()},30000)}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,500)});else setTimeout(init,500);
})();