(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
var APP_URL='https://umar-vai.github.io/Lottery-/';
var TELEGRAM_URL='https://t.me/lotmanager';
var state={session:null,user:null,profile:null,timer:null};
function $(id){return document.getElementById(id)}
function sessionKey(){return 'sb-'+REF+'-auth-token'}
function unpack(x){if(!x)return null;if(x.access_token)return x;if(x.currentSession&&x.currentSession.access_token)return x.currentSession;if(x.session&&x.session.access_token)return x.session;if(x.data&&x.data.session&&x.data.session.access_token)return x.data.session;return null}
function readSession(){try{var keys=[sessionKey()];for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(REF)>=0&&k.indexOf('auth')>=0&&keys.indexOf(k)<0)keys.push(k)}for(var j=0;j<keys.length;j++){var raw=localStorage.getItem(keys[j]);if(!raw)continue;try{var s=unpack(JSON.parse(raw));if(s)return s}catch(e){}}return null}catch(e){return null}}
function api(path,opt,token){opt=opt||{};var h=Object.assign({},opt.headers||{});h.apikey=KEY;if(token)h.Authorization='Bearer '+token;if(opt.body)h['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:h})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.message)||(d&&d.error_description)||(d&&d.error)||('HTTP '+r.status));return d})})}
function credits(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})+' credits'}
function navHtml(){return '<header class="draw01-global-header"><div class="draw01-global-nav">'+'<a class="d01-brand" href="./" aria-label="DRAW 01 home"><span class="d01-brand-mark"></span><span>DRAW//01</span></a>'+'<div class="d01-nav-center"><a class="d01-nav-link" href="./#events">Events</a><span class="d01-live"><i></i>LIVE SYSTEM</span></div>'+'<div class="d01-nav-right">'+'<div class="d01-credit-wrap" id="d01CreditWrap" hidden><button class="d01-credit-pill" id="d01CreditBtn" type="button" aria-haspopup="true" aria-expanded="false"><span class="d01-credit-icon">C</span><span class="d01-credit-label">Credit</span><strong id="d01CreditValue">0 credits</strong></button><div class="d01-credit-popover" id="d01CreditPopover"><span>Virtual credits</span><button class="d01-add-credit" id="d01AddCredit" type="button">＋ Add Credit</button><button class="d01-support-button" id="d01SupportBtn" type="button">♥ Support Points</button><a class="d01-telegram" id="d01TelegramLink" href="'+TELEGRAM_URL+'" target="_blank" rel="noopener noreferrer"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21.7 3.3 18.5 20c-.2 1.2-.9 1.5-1.9.9l-4.9-3.6-2.4 2.3c-.3.3-.5.5-1 .5l.4-5 9.1-8.2c.4-.4-.1-.6-.6-.2L6 13.8 1.2 12.3c-1-.3-1.1-1 .2-1.5L20 3.6c.9-.3 1.7.2 1.7-.3Z"/></svg><span>Telegram here</span></a></div></div>'+'<a class="d01-admin-link" id="adminNavLink" href="ops-v4.html" hidden>Admin Panel</a>'+'<button class="d01-login" id="loginBtn" type="button">Continue with Google</button>'+'<div class="d01-account" id="accountCard" hidden><img id="userAvatar" alt=""><strong id="userName">Player</strong><button class="d01-logout" id="logoutBtn" type="button">Log out</button></div>'+'</div></div><div class="d01-legacy-compat" aria-hidden="true"><span id="userEmail"></span><div id="balancePill"><strong id="balanceValue">0 credits</strong></div><img id="avatar" alt=""><strong id="name">Player</strong><span id="email"></span><strong id="adminName">Admin</strong><span id="adminEmail"></span><button id="topCreate" type="button"></button></div></header>'}
function footerHtml(){return '<footer class="draw01-global-footer"><div class="d01-footer-line"></div><div class="d01-footer-grid"><div><div class="d01-footer-brand">DRAW//01</div><div class="d01-footer-copy">Simulation/testing system only — virtual credits have no cash value. Development Support Points are separate and cannot be used for draws, tickets, odds or prizes.</div></div><div class="d01-footer-links"><a href="about.html">About & Contact</a><a href="privacy.html">Privacy Policy</a><a href="terms.html">Terms of Service</a></div></div></footer>'}
function loadAsset(tag,attr,url,key){if(document.querySelector(tag+'['+attr+'="'+key+'"]'))return;var e=document.createElement(tag);if(tag==='link'){e.rel='stylesheet';e.href=url}else{e.src=url;e.defer=true}e.setAttribute(attr,key);document.head.appendChild(e)}
function loadReadability(){loadAsset('link','data-d01-readability','readability.css?v=3','1');loadAsset('link','data-d01-motifs','site-motifs.css?v=1','1');loadAsset('link','data-d01-credit-center','credit-center.css?v=1','1');loadAsset('script','data-d01-credit-center','credit-center.js?v=1','1');loadAsset('link','data-d01-support-center','support-center.css?v=1','1');loadAsset('script','data-d01-support-center','support-center.js?v=1','1');if(/ops-v4\.html$/i.test(location.pathname)){loadAsset('link','data-d01-credit-admin','credit-admin.css?v=1','1');loadAsset('script','data-d01-credit-admin','credit-admin.js?v=1','1');loadAsset('link','data-d01-support-admin','support-admin.css?v=1','1');loadAsset('script','data-d01-support-admin','support-admin.js?v=1','1')}}
function install(){loadReadability();var old=document.querySelector('header.topbar, header.legal-top');if(old)old.replaceWith((function(){var x=document.createElement('div');x.innerHTML=navHtml();return x.firstElementChild})());else if(!document.querySelector('.draw01-global-header'))document.body.insertAdjacentHTML('afterbegin',navHtml());document.querySelectorAll('footer:not(.draw01-global-footer), .legal-footer').forEach(function(f){f.remove()});if(!document.querySelector('.draw01-global-footer'))document.body.insertAdjacentHTML('beforeend',footerHtml());bind();mirrorLegacy();render();refresh();setTimeout(refresh,250);setTimeout(refresh,1200)}
function bind(){var credit=$('d01CreditBtn'),wrap=$('d01CreditWrap');if(credit)credit.onclick=function(e){e.stopPropagation();wrap.classList.toggle('open');credit.setAttribute('aria-expanded',wrap.classList.contains('open')?'true':'false')};var add=$('d01AddCredit');if(add)add.onclick=function(e){e.stopPropagation();wrap.classList.remove('open');credit&&credit.setAttribute('aria-expanded','false');if(window.Draw01CreditCenter)window.Draw01CreditCenter.open();else setTimeout(function(){if(window.Draw01CreditCenter)window.Draw01CreditCenter.open()},250)};var support=$('d01SupportBtn');if(support)support.onclick=function(e){e.stopPropagation();wrap.classList.remove('open');credit&&credit.setAttribute('aria-expanded','false');if(window.Draw01SupportCenter)window.Draw01SupportCenter.open();else setTimeout(function(){if(window.Draw01SupportCenter)window.Draw01SupportCenter.open()},250)};document.addEventListener('click',function(e){if(wrap&&!wrap.contains(e.target)){wrap.classList.remove('open');credit&&credit.setAttribute('aria-expanded','false')}});var login=$('loginBtn');if(login)login.onclick=function(){if(/event\.html$/.test(location.pathname)){var slug=new URLSearchParams(location.search).get('e');if(slug)localStorage.setItem('draw01_post_login_event',slug)}location.href=BASE+'/auth/v1/authorize?provider=google&redirect_to='+encodeURIComponent(APP_URL)};var logout=$('logoutBtn');if(logout)logout.onclick=function(){var s=state.session||readSession(),token=s&&s.access_token;Promise.resolve(token?api('/auth/v1/logout',{method:'POST'},token):null).catch(function(){}).finally(function(){for(var i=localStorage.length-1;i>=0;i--){var k=localStorage.key(i);if(k&&k.indexOf('sb-'+REF)===0)localStorage.removeItem(k)}location.href='./'})}}
function mirrorLegacy(){var bal=$('balanceValue'),wallet=$('walletBalance');if(bal&&window.MutationObserver)new MutationObserver(function(){var n=parseFloat(String(bal.textContent||'0').replace(/[^0-9.-]/g,''));if(!isNaN(n))setBalance(n)}).observe(bal,{characterData:true,childList:true,subtree:true});if(wallet&&window.MutationObserver)new MutationObserver(function(){var n=parseFloat(String(wallet.textContent||'0').replace(/[^0-9.-]/g,''));if(!isNaN(n))setBalance(n)}).observe(wallet,{characterData:true,childList:true,subtree:true})}
function render(){var signed=!!state.user,login=$('loginBtn'),account=$('accountCard'),credit=$('d01CreditWrap'),admin=$('adminNavLink');document.documentElement.classList.toggle('d01-authenticated',signed);if(login)login.hidden=signed;if(account)account.hidden=!signed;if(credit)credit.hidden=!signed;if(admin)admin.hidden=!(signed&&state.profile&&state.profile.role==='admin');if(!signed)return;var m=state.user.user_metadata||{},p=state.profile||{};var name=p.display_name||m.full_name||m.name||(state.user.email?state.user.email.split('@')[0]:'Player');if($('userName'))$('userName').textContent=name;if($('userAvatar')){$('userAvatar').src=p.avatar_url||m.avatar_url||('https://ui-avatars.com/api/?name='+encodeURIComponent(name));$('userAvatar').alt=name+' avatar'}setBalance(p.balance||0)}
function setBalance(v){if($('d01CreditValue'))$('d01CreditValue').textContent=credits(v)}
function refresh(sessionOverride){var s=sessionOverride&&sessionOverride.access_token?sessionOverride:(state.session&&state.session.access_token?state.session:readSession());state.session=s;if(!s||!s.access_token){state.user=null;state.profile=null;render();return Promise.resolve(null)}return api('/auth/v1/user',{},s.access_token).then(function(u){state.user=u;render();return api('/rest/v1/profiles?select=id,display_name,avatar_url,role,balance&id=eq.'+encodeURIComponent(u.id)+'&limit=1',{},s.access_token).then(function(rows){state.profile=rows&&rows[0]?rows[0]:null;render();return state.profile}).catch(function(){state.profile=null;render();return null})}).catch(function(){var fallback=unpack(s);if(fallback&&fallback.user){state.user=fallback.user;render();return null}state.user=null;state.profile=null;render();return null})}
window.Draw01Shell={refresh:refresh,setBalance:setBalance,setSession:function(s){state.session=s||null;if(s&&s.user){state.user=s.user;render()}else if(!s){state.user=null;state.profile=null;render()}return refresh(s)},getProfile:function(){return state.profile}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();state.timer=setInterval(function(){refresh()},12000)
})();