(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
var S={session:null,data:null};
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function unpack(x){if(!x)return null;if(x.access_token)return x;if(x.currentSession&&x.currentSession.access_token)return x.currentSession;if(x.session&&x.session.access_token)return x.session;if(x.data&&x.data.session&&x.data.session.access_token)return x.data.session;return null}
function readSession(){try{var keys=['sb-'+REF+'-auth-token'];for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(REF)>=0&&k.indexOf('auth')>=0&&keys.indexOf(k)<0)keys.push(k)}for(var j=0;j<keys.length;j++){var raw=localStorage.getItem(keys[j]);if(!raw)continue;try{var s=unpack(JSON.parse(raw));if(s)return s}catch(e){}}}catch(e){}return null}
function req(body){S.session=readSession();if(!S.session) return Promise.reject(new Error('Admin session required'));return fetch(BASE+'/functions/v1/support-device-admin',{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+S.session.access_token,'Content-Type':'application/json'},body:JSON.stringify(body||{})}).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.error)||(d&&d.message)||('HTTP '+r.status));return d})})}
function fmt(v){return v?new Date(v).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Never'}
function install(){var host=$('overview');if(!host){setTimeout(install,300);return}if($('supportAdminPanel'))return;host.insertAdjacentHTML('afterbegin','<article id="supportAdminPanel" class="support-admin-panel"><div class="support-admin-head"><div><span class="eyebrow">PHONE BRIDGE · SUPPORT POINTS</span><h2>Real bKash support verification</h2><p>Link your Android phone, sync received-money SMS data, and let supporters claim non-draw Support Points. Support Points never affect tickets, odds or prizes.</p></div><button id="supportCreateDevice" class="btn primary compact" type="button">+ Link phone</button></div><div id="supportTokenBox" class="support-token" hidden><b>Copy this device token now — it is only shown once.</b><code id="supportTokenValue"></code><div class="support-token-actions"><button id="supportCopyToken" type="button">Copy token</button><a href="bridge.html" target="_blank" rel="noopener">Open Phone Bridge ↗</a></div></div><div class="support-admin-grid"><section class="support-box"><h3>Linked phones</h3><div id="supportDeviceList"><div class="support-admin-empty">Loading devices…</div></div></section><section class="support-box"><h3>Recent verified SMS transfers</h3><div id="supportTxList"><div class="support-admin-empty">Loading transfers…</div></div></section></div></article>');
$('supportCreateDevice').onclick=createDevice;$('supportCopyToken').onclick=function(){var t=$('supportTokenValue').textContent;navigator.clipboard&&navigator.clipboard.writeText(t).then(function(){$('supportCopyToken').textContent='Copied ✓';setTimeout(function(){$('supportCopyToken').textContent='Copy token'},1600)})};load()}
function render(){var d=S.data||{},devices=d.devices||[],tx=d.transactions||[];var dl=$('supportDeviceList'),tl=$('supportTxList');dl.innerHTML=devices.length?devices.map(function(x){return '<div class="support-device"><div><strong>'+esc(x.label)+'</strong><span>'+(x.enabled?'Enabled':'Disabled')+' · Last seen '+esc(fmt(x.last_seen_at))+'</span></div><button data-id="'+esc(x.id)+'" data-action="'+(x.enabled?'revoke':'enable')+'" class="'+(x.enabled?'danger':'')+'">'+(x.enabled?'Disable':'Enable')+'</button></div>'}).join(''):'<div class="support-admin-empty">No linked phone yet.</div>';dl.querySelectorAll('button[data-id]').forEach(function(b){b.onclick=function(){toggleDevice(b.dataset.id,b.dataset.action)}});tl.innerHTML=tx.length?tx.map(function(x){return '<div class="support-tx"><div><strong>TrxID '+esc(x.trx_id)+' · ****'+esc(x.sender_last4)+'</strong><span>'+esc(fmt(x.received_at))+(x.claimed_by_name?' · Claimed by '+esc(x.claimed_by_name):'')+'</span></div><div><b>৳'+esc(Number(x.amount||0).toLocaleString(undefined,{maximumFractionDigits:2}))+'</b><br><em class="'+(x.claimed_at?'':'pending')+'">'+(x.claimed_at?'Claimed':'Unclaimed')+'</em></div></div>'}).join(''):'<div class="support-admin-empty">No synced transfer yet.</div>'}
function load(){req({action:'list'}).then(function(d){S.data=d;render()}).catch(function(e){var dl=$('supportDeviceList');if(dl)dl.innerHTML='<div class="support-admin-empty">'+esc(e.message)+'</div>'})}
function createDevice(){var label=prompt('Phone label','My Android Phone');if(label===null)return;label=label.trim();if(!label)return;req({action:'create',label:label}).then(function(d){$('supportTokenValue').textContent=d.deviceToken||'';$('supportTokenBox').hidden=false;return load()}).catch(function(e){alert(e.message)})}
function toggleDevice(id,action){req({action:action,id:id}).then(load).catch(function(e){alert(e.message)})}
window.Draw01SupportAdmin={refresh:load};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();