(function(){
'use strict';
var BASE='https://mwtlsnneooxmryondrex.supabase.co';
var KEY='sb_publishable_zfXYDH1qSZURp8bRHgnBrQ_7t7-3BMd';
var REF='mwtlsnneooxmryondrex';
var S={session:null,user:null,claims:[]};
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function unpack(x){if(!x)return null;if(x.access_token)return x;if(x.currentSession&&x.currentSession.access_token)return x.currentSession;if(x.session&&x.session.access_token)return x.session;if(x.data&&x.data.session&&x.data.session.access_token)return x.data.session;return null}
function readSession(){try{var keys=['sb-'+REF+'-auth-token'];for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf(REF)>=0&&k.indexOf('auth')>=0&&keys.indexOf(k)<0)keys.push(k)}for(var j=0;j<keys.length;j++){var raw=localStorage.getItem(keys[j]);if(!raw)continue;try{var s=unpack(JSON.parse(raw));if(s)return s}catch(e){}}}catch(e){}return null}
function req(path,opt){opt=opt||{};var h=Object.assign({apikey:KEY},opt.headers||{});if(S.session&&S.session.access_token)h.Authorization='Bearer '+S.session.access_token;if(opt.body)h['Content-Type']='application/json';return fetch(BASE+path,Object.assign({},opt,{headers:h})).then(function(r){return r.text().then(function(t){var d;try{d=t?JSON.parse(t):null}catch(e){d=t}if(!r.ok)throw new Error((d&&d.error)||(d&&d.message)||(d&&d.details)||('HTTP '+r.status));return d})})}
function fmt(v){return v?new Date(v).toLocaleString([], {month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'—'}
function pts(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})+' Support Points'}
function install(){if($('d01SupportCenter'))return;document.body.insertAdjacentHTML('beforeend','<div id="d01SupportCenter" class="d01-support-center" hidden><section class="sp-shell" role="dialog" aria-modal="true" aria-labelledby="spTitle"><header class="sp-head"><div><small>DEVELOPMENT SUPPORT</small><h2 id="spTitle">Support Points</h2><p>Verify a bKash support transfer and keep a separate supporter balance.</p></div><button id="spClose" class="sp-close" type="button" aria-label="Close">×</button></header><div class="sp-body"><div class="sp-summary"><article class="sp-balance"><span>Your supporter balance</span><strong id="spBalance">0 Support Points</strong><small>1 BDT = 1 Support Point for this support system.</small></article><article class="sp-rules"><strong>Separate from DRAW credits</strong><p>Support Points cannot buy draw tickets, increase odds, unlock prize eligibility, be withdrawn, or be converted into cash. They only record support for development.</p></article></div><div class="sp-grid"><article class="sp-panel"><h3>Verify bKash transfer</h3><p>First sync the received-money SMS through your linked Phone Bridge. Then enter the sender number and TrxID below.</p><form id="spForm"><label class="sp-label"><span>Sender bKash number</span><input id="spSender" inputmode="tel" autocomplete="off" placeholder="01XXXXXXXXX" required></label><label class="sp-label"><span>Transaction ID (TrxID)</span><input id="spTrx" autocomplete="off" autocapitalize="characters" placeholder="e.g. BCD123XYZ" required></label><label class="sp-check"><input id="spTerms" type="checkbox"><span>I understand this is a development-support record. The resulting Support Points cannot be used for any draw, ticket, odds or prize.</span></label><button id="spSubmit" class="sp-submit" type="submit">Verify & add Support Points</button><div id="spMsg" class="sp-msg"></div></form><div class="sp-help">Phone Bridge setup is available to the site admin. Open <a href="bridge.html" target="_blank" rel="noopener">DRAW//01 Phone Bridge</a> on the Android phone after creating a device token in Admin Panel.</div></article><article class="sp-panel"><h3>Support history</h3><p>Only successfully verified transfers appear here.</p><div id="spHistory" class="sp-history"><div class="sp-empty">Loading…</div></div></article></div></div></section></div>');
$('spClose').onclick=close;var c=$('d01SupportCenter');c.addEventListener('click',function(e){if(e.target===c)close()});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!c.hidden)close()});$('spForm').onsubmit=claim}
function msg(t,err){var n=$('spMsg');if(!n)return;n.textContent=t||'';n.className='sp-msg'+(err?' err':'')}
function renderHistory(){var r=$('spHistory');if(!r)return;if(!S.claims.length){r.innerHTML='<div class="sp-empty">No verified support transfer yet.</div>';return}r.innerHTML=S.claims.map(function(x){return '<article class="sp-row"><div><strong>+'+esc(pts(x.points))+'</strong><span>'+esc(fmt(x.created_at))+'</span></div><b>৳'+esc(Number(x.amount_bdt||0).toLocaleString(undefined,{maximumFractionDigits:2}))+'</b></article>'}).join('')}
function load(){S.session=readSession();if(!S.session){msg('Please sign in with Google first.',true);if($('spBalance'))$('spBalance').textContent='Sign in required';return Promise.resolve()}return req('/auth/v1/user').then(function(u){S.user=u;return Promise.all([req('/rest/v1/support_wallets?select=balance&user_id=eq.'+encodeURIComponent(u.id)+'&limit=1'),req('/rest/v1/support_point_claims?select=id,amount_bdt,points,balance_after,created_at&user_id=eq.'+encodeURIComponent(u.id)+'&order=created_at.desc&limit=30')])}).then(function(x){var bal=x[0]&&x[0][0]?x[0][0].balance:0;S.claims=x[1]||[];$('spBalance').textContent=pts(bal);renderHistory();msg('')}).catch(function(e){msg(e.message,true)})}
function claim(e){e.preventDefault();S.session=readSession();if(!S.session){msg('Please sign in first.',true);return}var sender=$('spSender').value.trim(),trx=$('spTrx').value.trim().toUpperCase();if(!/^01\d{9}$/.test(sender)){msg('Enter a valid 11-digit bKash sender number.',true);return}if(!/^[A-Z0-9]{6,32}$/.test(trx)){msg('Enter a valid TrxID.',true);return}if(!$('spTerms').checked){msg('Please confirm the Support Points terms.',true);return}var b=$('spSubmit');b.disabled=true;b.textContent='Verifying…';msg('');req('/functions/v1/claim-support-points',{method:'POST',body:JSON.stringify({senderNumber:sender,trxId:trx,acceptedTerms:true})}).then(function(d){$('spSender').value='';$('spTrx').value='';$('spTerms').checked=false;msg('Verified. '+pts(d.points||d.amount||0)+' added to your supporter balance.');return load()}).catch(function(err){msg(err.message,true)}).finally(function(){b.disabled=false;b.textContent='Verify & add Support Points'})}
function open(){install();var c=$('d01SupportCenter');c.hidden=false;document.body.style.overflow='hidden';load()}
function close(){var c=$('d01SupportCenter');if(c)c.hidden=true;document.body.style.overflow=''}
window.Draw01SupportCenter={open:open,close:close,refresh:load};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();